config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, controllers: {
    sessions: "users/sessions",
    registrations: "users/registrations"
  }
  devise_scope :user do
    # get から root に帰る時は/を#に変える
    root "users/sessions#new"
    # get '/sign_in', to: 'users/sessions#new'
    get "signup", :to => "users/registrations#new"
    get "signin", :to => "users/sessions#new"
    get "signout", :to => "users/sessions#destroy"
  end
  mount LetterOpenerWeb::Engine, at: "/letter_opener" if Rails.env.development?

  namespace :users do
    get 'dash_boards/index'
    resources :articles   
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user

  validates :title, presence: true, length: { maximum: 10 }
  validates :content, presence: true

  mount_uploader :image, ImageUploader 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name,  presence: true
  has_many :article, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # deviseのコントローラを使う前に呼ばれるアクション
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    # 新規登録時にnicknameの取得を許可
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # 情報更新時にnicknameの取得を許可
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/users/articles_controller.rb
class Users::ArticlesController < ApplicationController
  before_action :set_article, only:[:show, :edit, :update, :destroy]

  def index
    @articles = current_user.article
  end  

  def new    
    @article = current_user.article.new
  end

  def create          
    @article = current_user.article.new(article_params)    
    if @article.save
      flash[:success] = '新規作成に成功しました。'
      redirect_to users_articles_url
    else
      flash[:danger] = '新規作成に失敗しました。'
      render :new
    end
  end
    
  def edit

  end

  def update
    if @article.update(article_params)
      flash[:success]="投稿を編集しました"
      redirect_to users_articles_url 
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    flash[:success]="投稿を削除しました"
    redirect_to users_articles_path 
  end  

  private

    def set_article
      @article = current_user.article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :content, :image)
    end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  def after_resending_confirmation_instructions_path_for(resource_name)
    super(resource_name)
  end

  # The path used after confirmation.
  def after_confirmation_path_for(resource_name, resource)
    super(resource_name, resource)
  end
end

app/controllers/users/dash_boards_controller.rb
class Users::DashBoardsController < ApplicationController
  def index
  end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end

  def after_sign_in_path_for(resource)
    users_dash_boards_index_path
  end

  def after_sign_out_path_for(resource)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeviseLesson</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/users/articles/edit.html.erb
<% provide(:title, 'edit') %>
<h1>記事の編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">    
    <%= form_with(model: @article, url:users_article_path, local: true) do |f| %>
      <%= f.label :title, class: "label-edit" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content, class: "label-edit" %>
      <%= f.text_area :content, class: "form-control" %>     

      <%= f.label :image, class: "label-edit" %>
      <%= f.file_field :image, class: "form-control" %>      

      <%= f.submit "更新する", class: "btn btn-primary btn-block btn-new" %>
      
    <% end %>
    <%= link_to "戻る", users_articles_path %>  
  </div>
</div>

app/views/users/articles/index.html.erb
<% provide(:title, 'All Articles') %>
<h1>記事一覧</h1>
<div class="col-md-10 col-md-offset-1">
  <table class="table table-condensed table-hover" id="table-articles">
    <div class="d-grid gap-2 col-6 mx-auto">
      <%= link_to "新規作成", new_users_article_path(id: current_user.id), class: "btn btn-lg btn-primary " %>
    </div>
    <thead>
      <tr>
        <th>詳細表示</th>
        <th>タイトル</th>
        <th>内容</th>
        <th>画像</th>
        <th>編集・削除</th>
      </tr>
    </thead>
    <body>
      <% @articles.each do |article| %>
        <tr>
          <td><%= link_to "詳細", users_article_path(article), class: "btn btn-primary" %></td>
          <td><%= article.title %></td>
          <td><%= article.content %></td>
          <td><%= image_tag article.image.url, class: 'rounded-circle mr15', width: '40', height: '40' %></td>
          <td>
            <%= link_to "編集", edit_users_article_path(article), class: "btn btn-success" %>
            <%= link_to "削除",  users_article_path(article), method: :delete, data: { confirm: "削除してもよろしいですか？" }, class: "btn btn-danger" %>
          </td>
        </tr>
      <% end %> 
    </body>
  </table>
</div>

app/views/users/articles/new.html.erb
<% provide(:title, 'New') %>
<h1>記事の新規作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">    
    <%= form_with(model: @article, url:users_articles_path, local: true) do |f| %>
      <%= f.label :title, class: "label-new" %>
      <%= f.text_field :title, class: "form-control" %>

      <%= f.label :content, class: "label-new" %>
      <%= f.text_area :content, class: "form-control" %>     

      <%= f.label :image, class: "label-new" %>
      <%= f.file_field :image, class: "form-control" %>      

      <%= f.submit "新規作成", class: "btn btn-primary btn-block btn-new" %>
      
    <% end %>
    <%= link_to "戻る", users_articles_path %>  
  </div>
</div>

app/views/users/articles/show.html.erb
<% provide(:title, "articles") %>
<div>
<h1>記事詳細</h1>
</div>

<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <table class="table table-hover" id="table-tasks">
      <thead>
        <tr>
          <th>タイトル</th>
          <th>内容</th>
          <th>画像</th>
        </tr>
      </thead>

      <tbody>       
        <tr>
          <td><%= @article.title %></td>
          <td><%= @article.content %></td>
          <td><%= image_tag @article.image.url, class: 'rounded-circle mr15', width: '40', height: '40' %></td>             
        </tr>        
      </tbody>
      
    </table>
    <div class = "btn">
      <%= link_to "編集", edit_users_article_path(id: @article.id), class: "btn btn-success btn-center" %>
      <%= link_to "削除", users_article_path(id: @article.id), method: :delete,class: "btn btn-danger btn-center" %><br>
      <%= link_to "記事一覧へ戻る", users_articles_path, class: "btn btn-lg btn-primary btn-center" %>
    </div>
  </div>    
</div>

app/views/users/dash_boards/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4 offset-4 text-center">
      <h1>Dash Boards</h1>
      <h2><%= current_user.name %></h2>
      <div class="d-grid gap-2 col-6 mx-auto">
        <%= link_to "記事一覧", users_articles_path, class: "btn btn-lg btn-primary btn-block" %> <br> 
        <%= link_to t('.edit'), edit_user_registration_path, class: "btn btn-lg btn-primary btn-block" %> <br>
        <%= link_to t('.signed_out'), signout_path, class: "btn btn-lg btn-warning btn-block" %>
      </div>
    </div>
  </div>
</div>